// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SRVP.Data;

#nullable disable

namespace SRVP.Migrations
{
    [DbContext(typeof(SRVPContext))]
    [Migration("20231114232417_primeraMigracion")]
    partial class primeraMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("SRVP.Data.Models.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<DateTime>("alta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("cuil")
                        .HasColumnType("integer");

                    b.Property<int>("dni")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("estadoCrediticio")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("fechaNacimiento")
                        .HasColumnType("date");

                    b.Property<bool>("habilitado")
                        .HasColumnType("boolean");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("vivo")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("SRVP.Data.Models.SistemaExterno", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("paginaRetorno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("secreto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("SistemasExternos");
                });

            modelBuilder.Entity("SRVP.Models.CodigoAcceso", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("creacion")
                        .HasColumnType("date");

                    b.Property<Guid>("sistemaExternoId")
                        .HasColumnType("uuid");

                    b.Property<int>("usuarioId")
                        .HasColumnType("integer");

                    b.Property<bool>("utilizado")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.ToTable("CodigosAccesos");
                });
#pragma warning restore 612, 618
        }
    }
}
